<a href="https://colab.research.google.com/github/Iswarya19-A/11239A007-/blob/main/EXP_5C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def hill_encrypt(plain_block, key_matrix):
    """Encrypt a block of 3 letters using the Hill cipher key matrix."""
    vec = np.array([ord(ch) - 65 for ch in plain_block])
    result = np.dot(key_matrix, vec) % 26
    return ''.join(chr(num + 65) for num in result)


def hill_decrypt(cipher_block, inv_key_matrix):
    """Decrypt a block of 3 letters using the inverse Hill cipher key matrix."""
    vec = np.array([ord(ch) - 65 for ch in cipher_block])
    result = np.dot(inv_key_matrix, vec) % 26
    return ''.join(chr(num + 65) for num in result)


def mod_inverse_matrix(matrix, modulus=26):
    """Compute the modular inverse of a 3x3 matrix under mod 26."""
    det = int(round(np.linalg.det(matrix))) % modulus
    det_inv = pow(det, -1, modulus)  # modular multiplicative inverse
    matrix_adj = np.round(det * np.linalg.inv(matrix)).astype(int) % modulus
    return (det_inv * matrix_adj) % modulus


def main():
    # Key matrix (invertible mod 26)
    key_matrix = np.array([[6, 24, 1],
                           [13, 16, 10],
                           [20, 17, 15]], dtype=int)

    print("Key Matrix:\n", key_matrix)

    # Compute inverse key matrix (for decryption)
    inv_key_matrix = mod_inverse_matrix(key_matrix)
    print("\nInverse Key Matrix:\n", inv_key_matrix)

    # Get input and prepare plaintext
    msg = input("\nEnter plain text (A–Z only): ").upper().replace(" ", "")
    while len(msg) % 3 != 0:
        msg += 'X'  # pad with X

    print("\nPlaintext (after padding):", msg)

    # Encrypt in blocks of 3
    cipher_text = ''
    for i in range(0, len(msg), 3):
        cipher_text += hill_encrypt(msg[i:i+3], key_matrix)

    print("\nEncrypted Cipher Text:", cipher_text)

    # Decrypt in blocks of 3
    decrypted_text = ''
    for i in range(0, len(cipher_text), 3):
        decrypted_text += hill_decrypt(cipher_text[i:i+3], inv_key_matrix)

    print("\nDecrypted Plain Text:", decrypted_text)


if __name__ == "__main__":
    main()


Key Matrix:
 [[ 6 24  1]
 [13 16 10]
 [20 17 15]]

Inverse Key Matrix:
 [[22 19 13]
 [ 0 22  3]
 [ 6  5 12]]

Enter plain text (A–Z only): ACT

Plaintext (after padding): ACT

Encrypted Cipher Text: POH

Decrypted Plain Text: LRK
